################
## DEPLOYMENT ##
################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  skillsets-api
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "demo-instrumentation"