apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
namePrefix: dev-

# Replaces SKILLSETS_API_IMAGE_NAME with the new image name and tag
images:
- name: KUSTOMIZE
  newName: codesenju/skillsets-api
  newTag: "1"

# Generate a configmap
configMapGenerator:
- literals:
  - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
  name: skillsets-api-config

replacements:
- source:
    fieldPath: metadata.name
    kind: Service
    name: skillsets-api
    version: v1
  targets:
  - fieldPaths:
    - spec.scaleTargetRef.name
    select:
      kind: HorizontalPodAutoscaler
      name: skillsets-api-hpa

patches:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: skillsets-api-ingress
    version: v1
- path: topology_spread_patch.yaml
- path: mem_cpu_patch.yaml
# Replace redis-secret key values with the following:
- patch: |-
    - op: replace
      path: /data/REDIS_HOST
      value: ZGV2LXNraWxsc2V0cy1yZWRpcy1kYi5kZXYuc3Zj
    - op: replace
      path: /data/REDIS_PASSWORD
      value: cmVkaXMxMjM0NQ==
  target:
    kind: Secret
    name: redis-secret

resources:
- ../base/
- redis.yaml