################
## DEPLOYMENT ##
################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  skillsets-api
spec:
  template:
    spec:
      topologySpreadConstraints:
      - maxSkew: 3
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: skillsets-api