apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: skillsets-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skillsets-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 3
        periodSeconds: 5
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 5
#---
#apiVersion: autoscaling/v2beta2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: skillsets-redis-db-hpa
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: StatefulSet
#    name: skillsets-redis-db
#  minReplicas: 3
#  maxReplicas: 20
#  metrics:
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: Utilization
#        averageUtilization: 60
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 60
#  behavior:
#    scaleUp:
#      policies:
#      - type: Pods
#        value: 3
#        periodSeconds: 5
#    scaleDown:
#      policies:
#      - type: Pods
#        value: 1
#        periodSeconds: 5