apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Redis Secret
secretGenerator:
- name: redis-secret
  literals:
  - REDIS_PASSWORD=12345
  - REDIS_HOST=localhost
  - REDIS_PORT="6379"

resources:
#  - namespace.yaml
  - deployment.yaml
  - service.yaml
#  - redis.yaml
  - ingress.yaml
  - hpa.yaml